version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nilerr
    - revive
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports
